#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

. ./common

CURIMG=stage6.$IMGFORMAT

install_packages() {
  onvm_chroot sh -l -ex - <<\EOF
apt-get install -y iw
EOF
{

cleanup_wireless_defaults() {
  onvm_chroot sh -l -ex - <<\EOF
# /etc/default/ifplugd
# replace defualt interfaces and hotplug interfaces
sed -i '/^INTERFACES/d' /etc/default/ifplugd
sed -i '/^HOTPLUG_INTERFACES/d' /etc/default/ifplugd
echo "INTERFACES=\"\" 
HOTPLUG_INTERFACES=\"eth0\"" >> /etc/default/ifplugd

# REALTEK DEFAULTS:
#  doesnt give a shit about dhcp/ifplugd/wpa_supplicant
#  interface needs to be UP in ifconfig to set mode
# RALINK defaults:
#  shits given about wpa_supplicant/ifplugd/etc
#  interface needs to be DOWN in ifconfig to set mode

# remove wpa_supplicant from /etc/network/if-* 
find /etc/network/if-* -name 'wpasupplicant' -exec rm -v {} \;

EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage5.$IMGFORMAT $CURIMG
dotask run_qemu $CURIMG
dotask mount_apt_cache
dotask disable_starting_services
dotask install_packages
dotask cleanup_wireless_defaults
dotask save_space_using_hardlink
dotask allow_starting_services
dotask update_issue
dotask fingerprint_debian
dotask shutdown_qemu
dotask finish_image
