#!/bin/sh
# Part of spindle http://asbradbury.org/projects/spindle
#
# See LICENSE file for copyright and license details

set -ex

. ./common

CURIMG=stage5.$IMGFORMAT

build_batman() {
  # we may want to break out DEBIAN_FRONTEND=noninteractive
  ssh_in_to_qemu chroot /mnt sh -l -ex - <<EOF
export KERNELPATH=/lib/modules/3.12.20+/build
wget http://downloads.open-mesh.org/batman/releases/batman-adv-2014.2.0/batman-adv-2014.2.0.tar.gz
tar -xvzf batman-adv-2014.2.0.tar.gz
cd batman-adv-2014.2.0
# EVIL MAKEFILE PATCHING
sed -i 's/depmod\ \-a/depmod 3.12.20\+/' Makefile
make && make install
cd ..
rm -rf batman-adv-2014.2.0*
echo "batman-adv" >> /etc/modules
# 
wget http://downloads.open-mesh.org/batman/releases/batman-adv-2014.2.0/batctl-2014.2.0.tar.gz
# remove me on next full rebuild
apt-get install libnl-3-dev
tar -xvzf batctl-2014.2.0*
cd batctl-2014.2.0
make && make install
cd ..
rm -rf batctl-2014.2.0*
#
wget http://downloads.open-mesh.org/batman/releases/batman-adv-2014.2.0/alfred-2014.2.0.tar.gz
tar -xvzf alfred-2014.2.0.tar.gz
cd alfred-2014.2.0
make && make install
cd ..
rm -rf alfred-2014.2.0* 
EOF
}

cleanup_ipv6() {
  onvm_chroot sh -l -ex - <<\EOF
rm /etc/modprobe.d/ipv6.conf
EOF
}

cd $WORKDIR
dotask branch_image ../$OUTDIR/stage4.$IMGFORMAT $CURIMG
dotask run_qemu $CURIMG
dotask mount_apt_cache
dotask disable_starting_services
dotask build_batman
dotask cleanup_ipv6
dotask save_space_using_hardlink
dotask allow_starting_services
dotask update_issue
dotask fingerprint_debian
dotask shutdown_qemu
dotask finish_image
